[package]
name = "helix-vcs"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
helix-core = { path = "../helix-core" }
helix-event = { path = "../helix-event" }
helix-stdx = { path = "../helix-stdx", features = ["tokio"] }

tokio = { version = "1", features = ["sync", "macros"] }
parking_lot.workspace = true
arc-swap.workspace = true

imara-diff =  "0.2.0"
anyhow = "1"

log = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "time", "parking_lot"] }
gix = { version = "0.80.0", default-features = false, features = ["attributes", "status", "max-performance"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1", features = ["rt"] }

[features]
git = ["gix"]

[dev-dependencies]
tempfile.workspace = true
